# Generated by Django 5.0.6 on 2024-06-06 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('carro', models.TextField()),
                ('servico', models.TextField()),
                ('telefone', models.TextField()),
                ('submiited_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
