# Generated by Django 5.0.7 on 2024-07-30 13:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_alter_contact_carro_alter_contact_servico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('idcli', models.AutoField(primary_key=True, serialize=False)),
                ('codcli', models.CharField(max_length=10)),
                ('nomecli', models.CharField(max_length=100)),
                ('razasoccli', models.CharField(max_length=100)),
                ('datacli', models.DateField()),
                ('cnpjcli', models.CharField(max_length=20)),
                ('fonecli', models.CharField(max_length=20)),
                ('cidcli', models.CharField(max_length=50)),
                ('estcli', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'cliente',
            },
        ),
        migrations.CreateModel(
            name='ClienteBkp',
            fields=[
                ('idcli', models.AutoField(primary_key=True, serialize=False)),
                ('codcli', models.CharField(max_length=10)),
                ('nomecli', models.CharField(max_length=100)),
                ('razasoccli', models.CharField(max_length=100)),
                ('datacli', models.DateField()),
                ('cnpjcli', models.CharField(max_length=20)),
                ('fonecli', models.CharField(max_length=20)),
                ('cidcli', models.CharField(max_length=50)),
                ('estcli', models.CharField(max_length=100)),
            ],
            options={
                'db_table': 'clientesbkp',
            },
        ),
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('idforn', models.AutoField(primary_key=True, serialize=False)),
                ('codiforn', models.CharField(max_length=10)),
                ('nomeforn', models.CharField(max_length=100)),
                ('razasocforn', models.CharField(max_length=100)),
                ('foneforn', models.CharField(max_length=20)),
            ],
            options={
                'db_table': 'fornecedor',
            },
        ),
        migrations.CreateModel(
            name='Vendedor',
            fields=[
                ('idvende', models.AutoField(primary_key=True, serialize=False)),
                ('codivende', models.CharField(max_length=10)),
                ('nomevende', models.CharField(max_length=100)),
                ('razasocvende', models.CharField(max_length=100)),
                ('fonevende', models.CharField(max_length=20)),
                ('porcvende', models.FloatField()),
            ],
            options={
                'db_table': 'vendedor',
            },
        ),
        migrations.CreateModel(
            name='Produto',
            fields=[
                ('idprod', models.AutoField(primary_key=True, serialize=False)),
                ('codiprod', models.CharField(max_length=20)),
                ('descprod', models.CharField(max_length=100)),
                ('valorprod', models.FloatField()),
                ('situprod', models.CharField(max_length=1)),
                ('idforn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fornecedor')),
            ],
            options={
                'db_table': 'produto',
            },
        ),
        migrations.CreateModel(
            name='Venda',
            fields=[
                ('idvend', models.AutoField(primary_key=True, serialize=False)),
                ('codivend', models.CharField(max_length=10)),
                ('valorvend', models.FloatField()),
                ('descvend', models.FloatField()),
                ('totalvend', models.FloatField()),
                ('datavend', models.DateField()),
                ('valorcomissao', models.DecimalField(decimal_places=2, max_digits=10)),
                ('idcli', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.cliente')),
                ('idforn', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.fornecedor')),
                ('idvende', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.vendedor')),
            ],
            options={
                'db_table': 'venda',
            },
        ),
        migrations.CreateModel(
            name='ItensVenda',
            fields=[
                ('iditvend', models.AutoField(primary_key=True, serialize=False)),
                ('valoritvend', models.FloatField()),
                ('qtditvend', models.IntegerField()),
                ('descitvend', models.FloatField()),
                ('idprod', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.produto')),
                ('idvend', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.venda')),
            ],
            options={
                'db_table': 'itensvenda',
            },
        ),
    ]
